service: product-service
#  name: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  httpApi:
    cors:
      allowedOrigins:
        - https://d3txv4isrw4dhz.cloudfront.net
        - http://localhost:3000
      allowedHeaders:
        - Content-Type
        # - Authorization
      allowedMethods:
        - GET

functions:
  getProductsList:
    handler: getProductsList.handler
    events:
      - httpApi:
          method: get
          path: /products
  getProductsById:
    handler: getProductsById.handler
    events:
      - httpApi:
          method: get
          path: /products/{productId}
